### ISSUE TITLE
Protocol Error (Browser.grantPermissions)

### ISSUE THREAD

**Issue by AbdulSayyed** [yhatt/marp-cli-example#15]
I ran the command `npx marp --preview ./slides/Deck.md` and I get the following error 

(node:9048) UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.grantPermissions): Unknown permission type: clipboardRead
    at K:\ABC-Docs\@Archives\2020\node-marp\node_modules\carlo\node_modules\puppeteer-core\lib\Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (K:\ABC-Docs\@Archives\2020\node-marp\node_modules\carlo\node_modules\puppeteer-core\lib\Connection.js:73:12)
    at BrowserContext.overridePermissions (K:\ABC-Docs\@Archives\2020\node-marp\node_modules\carlo\node_modules\puppeteer-core\lib\Browser.js:349:28)
    at BrowserContext.<anonymous> (K:\ABC-Docs\@Archives\2020\node-marp\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:109:23)
    at App.init_ (K:\ABC-Docs\@Archives\2020\node-marp\node_modules\carlo\lib\carlo.js:62:11)
    at Object.launch (K:\ABC-Docs\@Archives\2020\node-marp\node_modules\carlo\lib\carlo.js:627:15)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:9048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
any suggestion ?

**Comment by yhatt** [comment]
FYI: https://github.com/marp-team/marp-cli/issues/190

**Comment by yhatt** [comment]
In the latest [Marp CLI v0.17.3](https://github.com/marp-team/marp-cli/releases/tag/v0.17.3), *`--preview` option has deprecated* due to the unmaintained dependent package carlo (https://github.com/GoogleChromeLabs/carlo/issues/163#issuecomment-592238093) and incompatible Chrome >= 81.

The current stable Chrome was supposed to be imcompatible version 81, *but [upcoming releases for Chrome >= 81 was paused due to adjusted schedules](https://chromereleases.googleblog.com/2020/03/upcoming-chrome-and-chrome-os-releases.html) probably affected by COVID-19*. `--preview` should work correctly as long as using stable Chrome 80.

To know what happening, plaese track https://github.com/marp-team/marp-cli/issues/211 instead of here.
